default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  timeout: 5000
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: rails_push_dev
  username: root
  password: password
